quarkus.hibernate-orm.log.sql=true
quarkus.log.category."com.akazukin".level=DEBUG

quarkus.otel.traces.exporter=cdi
quarkus.otel.exporter.otlp.enabled=false

quarkus.log.console.json=false

quarkus.redis.devservices.enabled=true
quarkus.redis.devservices.port=6379
