# Seed initial users on first startup
akazukin.dev.seed.enabled=true

quarkus.hibernate-orm.log.sql=true
quarkus.log.category."com.akazukin".level=DEBUG
quarkus.log.category."io.quarkus.smallrye.jwt".level=TRACE
quarkus.log.category."io.smallrye.jwt".level=TRACE

quarkus.http.port=38081

quarkus.sqs.devservices.enabled=false
quarkus.dynamodb.devservices.enabled=false
quarkus.secretsmanager.devservices.enabled=false

quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:${user.home}/.akazukin/data/akazukin-dev;AUTO_SERVER=TRUE
quarkus.datasource.username=sa
quarkus.datasource.password=
quarkus.hibernate-orm.database.generation=update
quarkus.flyway.migrate-at-start=false

quarkus.otel.traces.exporter=cdi
quarkus.otel.exporter.otlp.enabled=false

quarkus.log.console.json=false

quarkus.redis.devservices.enabled=false
quarkus.redis.health.enabled=false
